stages:
  data_ingestion:
    cmd: python3 src/kidney/pipeline/stage_01_data_ingestion.py
    deps:
      - src/kidney/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/kidney-ct-scan-image
      - artifacts/data_ingestion/data.zip

  base_model:
    cmd: python3 src/kidney/pipeline/stage_02_base_model.py
    deps:
      - src/kidney/pipeline/stage_02_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/base_model

  training:
    cmd: python3 src/kidney/pipeline/stage_03_model_training.py
    deps:
      - src/kidney/pipeline/stage_03_model_training.py
      - src/kidney/components/callbacks.py
      - config/config.yaml
      - artifacts/data_ingestion/kidney-ct-scan-image
      - artifacts/base_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - artifacts/model_training/model.h5
