artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1V0MCnx7Hw_S2Avh7VQslLLxp6cBx4Ql2/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

base_model:
  root_dir: artifacts/base_model
  base_model_path: artifacts/base_model/base_model.h5
  updated_base_model_path: artifacts/base_model/base_model_updated.h5

call_backs:
  root_dir: artifacts/call_backs
  tensorboard_root_log_dir: artifacts/call_backs/tensorboard_log_dir
  checkpoint_model_filepath: artifacts/call_backs/checkpoint_dir/model.h5

model_training:
  root_dir: artifacts/model_training
  model_trained_path: artifacts/model_training/model.h5

model_evaluation:
  path_of_model: artifacts/model_training/model.h5
  training_data: artifacts/data_ingestion/kidney-ct-scan-image
  mlflow_uri: https://dagshub.com/fraidoon_omarzai/end-to-end-kidney-tumor.mlflow
